### ISSUE TITLE
`The system` should be able to `manage user wallets` so that `wallets may be associated to users`

### ISSUE THREAD

**Issue by marcellodesales** [marcellodesales/kraken-the-btc-transactions#2]
* Add a wallet address to an existing user

> * **Wesley Crusher**: `mvd6qFeVkqH6MNAS2Y2cLifbdaX5XUkbZJ`

**Comment by marcellodesales** [comment]
# 💡 Resolution

* PR #9, for Requirement #1 , resolved this capability as we can associate users 

# Use Case

* Create Users
* Create Wallets
* Associate a Wallet to a User

## 👤 Create User 

* Create and verify

```console
$ curl -i "http://localhost:4565/users" \
  -X POST -H "Content-Type: application/json" \
  -d '{ "first_name": "Marcello", "last_name": "DeSales", "origin": "ws" }'
HTTP/1.1 201 Created
```
```yaml
Transfer-Encoding: chunked
Date: Tue, 12 Apr 2022 04:59:24 GMT
Server: postgrest/9.0.0.20220211 (pre-release)
Content-Range: */*
```

* Verify

```console
$ curl -i -X GET "localhost:4565/users?first_name=eq.Marcello"
HTTP/1.1 200 OK
```
```yaml
Transfer-Encoding: chunked
Date: Tue, 12 Apr 2022 07:52:20 GMT
Server: postgrest/9.0.0.20220211 (pre-release)
Content-Range: 0-0/*
Content-Location: /users?first_name=eq.Marcello
Content-Type: application/json; charset=utf-8
```
```json
[{"user_id":11,"first_name":"Marcello","last_name":"DeSales","created_at":"2022-04-12T04:59:31.382149+00:00","origin":"ws"}]
```

## 🤑  Create Wallets

```console
$ curl -i "http://localhost:4565/wallets" \
  -X POST -H "Content-Type: application/json" \
  -d '{ "wallet_address": "3LecPPoHhBtdn4NB8hBWuwAyAegviTqSid" }'
HTTP/1.1 201 Created
Transfer-Encoding: chunked
Date: Tue, 12 Apr 2022 07:53:54 GMT
Server: postgrest/9.0.0.20220211 (pre-release)
Content-Range: */*
```

## 🍰 Associate a Wallet to a User

* Associate the wallet created with the user ID above

```console
$ curl -i "http://localhost:4565/wallets_x_users" \
  -X POST -H "Content-Type: application/json" \
  -d '{ "wallet_address": "3LecPPoHhBtdn4NB8hBWuwAyAegviTqSid", "user_id": 11 }'
HTTP/1.1 201 Created
Transfer-Encoding: chunked
Date: Tue, 12 Apr 2022 07:54:34 GMT
Server: postgrest/9.0.0.20220211 (pre-release)
Content-Range: */*
```

* Verify if it user is listed with the wallet

```console
$ curl -i -X GET "localhost:4565/wallets_x_users?select=wallet_address,user_id,users(first_name,last_name)"
HTTP/1.1 200 OK
```
```yaml
Transfer-Encoding: chunked
Date: Tue, 12 Apr 2022 07:54:56 GMT
Server: postgrest/9.0.0.20220211 (pre-release)
Content-Range: 0-7/*
Content-Location: /wallets_x_users?select=wallet_address%2Cuser_id%2Cusers%28first_name%2Clast_name%29
Content-Type: application/json; charset=utf-8
```
```json
[{"wallet_address":"mvd6qFeVkqH6MNAS2Y2cLifbdaX5XUkbZJ","user_id":1,"users":{"first_name":"Wesley","last_name":"Crusher"}},
 {"wallet_address":"mmFFG4jqAtw9MoCC88hw5FNfreQWuEHADp","user_id":2,"users":{"first_name":"Leonard","last_name":"McCoy"}},
 {"wallet_address":"mzzg8fvHXydKs8j9D2a8t7KpSXpGgAnk4n","user_id":3,"users":{"first_name":"Jonathan","last_name":"Archer"}},
 {"wallet_address":"2N1SP7r92ZZJvYKG2oNtzPwYnzw62up7mTo","user_id":4,"users":{"first_name":"Jadzia","last_name":"Dax"}},
 {"wallet_address":"mutrAf4usv3HKNdpLwVD4ow2oLArL6Rez8","user_id":5,"users":{"first_name":"Montgomery","last_name":"Scott"}},
 {"wallet_address":"miTHhiX3iFhVnAEecLjybxvV5g8mKYTtnM","user_id":6,"users":{"first_name":"James","last_name":"T. Kirk"}},
 {"wallet_address":"mvcyJMiAcSXKAEsQxbW9TYZ369rsMG6rVV","user_id":7,"users":{"first_name":"Spock","last_name":null}},
 {"wallet_address":"3LecPPoHhBtdn4NB8hBWuwAyAegviTqSid","user_id":11,"users":{"first_name":"Marcello","last_name":"DeSales"}}]%
```

* We can also project the user

```console
$ curl -i -X GET "localhost:4565/wallets_x_users?select=wallet_address,user_id,users(first_name,last_name)&wallet_address=eq.3LecPPoHhBtdn4NB8hBWuwAyAegviTqSid"
HTTP/1.1 200 OK
```
```yaml
Transfer-Encoding: chunked
Date: Tue, 12 Apr 2022 08:03:21 GMT
Server: postgrest/9.0.0.20220211 (pre-release)
Content-Range: 0-0/*
Content-Location: /wallets_x_users?select=wallet_address%2Cuser_id%2Cusers%28first_name%2Clast_name%29&wallet_address=eq.3LecPPoHhBtdn4NB8hBWuwAyAegviTqSid
Content-Type: application/json; charset=utf-8
```
```json
[{"wallet_address":"3LecPPoHhBtdn4NB8hBWuwAyAegviTqSid","user_id":11,"users":{"first_name":"Marcello","last_name":"DeSales"}}]%
```
