### ISSUE TITLE
`The system` should be able to `manage wallet transactions` so that `transactions can be stored for processing`

### ISSUE THREAD

**Issue by marcellodesales** [marcellodesales/kraken-the-btc-transactions#3]
* Unique transactions can be added
* Unique transactions can be removed

# 🎉 Resolved

* PR #9 resolved this ticket, as the database API service implements everything...

# ✅ Verification

* We can CRUD transactions

## Create Wallet Transactions

* Only for existing wallets

```console
$ curl -i "http://localhost:4565/wallet_transactions" -X POST -H "Content-Type: application/json" 
  -d '{  
         "txid": "7b9cfbed67d423e51ec31b4887764710a496d8c6b7f5d32d9fe6387af3471915", 
          "wallet_address": "3LecPPoHhBtdn4NB8hBWuwAyAegviTqSid", "amount": 8.56 
        }'
HTTP/1.1 201 Created
```
```yaml
Transfer-Encoding: chunked
Date: Tue, 12 Apr 2022 08:18:25 GMT
Server: postgrest/9.0.0.20220211 (pre-release)
Content-Range: */*
```

## Retrieve the Transaction information

```console
$ curl -i -X GET "localhost:4565/wallet_transactions?
         select=txid,wallet_address,amount,category,wallets(created_at)&
         wallet_address=eq.3LecPPoHhBtdn4NB8hBWuwAyAegviTqSid"
HTTP/1.1 200 OK
```
```yaml
Transfer-Encoding: chunked
Date: Tue, 12 Apr 2022 08:22:15 GMT
Server: postgrest/9.0.0.20220211 (pre-release)
Content-Range: 0-0/*
Content-Location: /wallet_transactions?select=txid%2Cwallet_address%2Camount%2Ccategory%2Cwallets%28created_at%29&wallet_address=eq.3LecPPoHhBtdn4NB8hBWuwAyAegviTqSid
Content-Type: application/json; charset=utf-8
```
```json
[
  {
  "txid":"7b9cfbed67d423e51ec31b4887764710a496d8c6b7f5d32d9fe6387af3471915",
  "wallet_address":"3LecPPoHhBtdn4NB8hBWuwAyAegviTqSid",
  "amount":8.56,
   "category":"receive",
   "wallets":{
         "created_at": "2022-04-12T07:53:54.246167+00:00"
    }
  }
]
```
